import OpenAI from "openai";
import { type ImageAnalysisFlags } from "@shared/image-analysis";

const API_KEY = process.env.OPENAI_API_KEY;

if (!API_KEY) {
  throw new Error("OPENAI_API_KEY environment variable is not set.");
}

const openai = new OpenAI({ apiKey: API_KEY });

const analysisSchema = {
  type: "object",
  properties: {
    ai_generation_analysis: {
      type: "object",
      description:
        "Deep analysis whether the image is AI-generated, including likelihood and evidence.",
      properties: {
        likelihood: {
          type: "string",
          description:
            "Likelihood the image is AI-generated: High | Medium | Low | Unlikely",
        },
        evidence: {
          type: "array",
          items: { type: "string" },
          description:
            "List of visual cues and artifacts explaining the AI likelihood.",
        },
        confidence_score: {
          type: "number",
          description: "Confidence level between 0.0 — 1.0",
        },
      },
      required: ["likelihood", "evidence", "confidence_score"],
    },
    is_photo: { type: "boolean" },
    is_animation: { type: "boolean" },
    has_human_face: { type: "boolean" },
    is_full_face_visible: { type: "boolean" },
    is_famous_person: { type: "boolean" },
    has_known_brand_or_character: { type: "boolean" },
    title: { type: "string" },
    description: { type: "string" },
  },
  required: [
    "ai_generation_analysis",
    "is_photo",
    "is_animation",
    "has_human_face",
    "is_full_face_visible",
    "is_famous_person",
    "has_known_brand_or_character",
    "title",
    "description",
  ],
} as const;

export async function analyzeImageWithOpenAI(
  base64Image: string,
  mimeType: string
): Promise<ImageAnalysisFlags> {
  try {
    const prompt = `
You are an expert forensic image analyst. Your task is to determine if this image is a real photograph or generated by AI. 
Use a zero-trust approach. Examine:

1. Hyper-realism or "too perfect"
2. Lighting consistency
3. Texture repetition
4. DOF/bokeh artifacts
5. Fine details (hands, edges, hair)

Your output MUST be valid JSON EXACTLY following the given schema.
Use simple language for 'evidence'.

- Title: 3–6 words
- Description: 1–2 sentences
`;

    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      response_format: { type: "json_schema", json_schema: { name: "ImageAnalysis", schema: analysisSchema, strict: true } },
      messages: [
        {
          role: "user",
          content: [
            {
              type: "image_url",
              image_url: {
                url: `data:${mimeType};base64,${base64Image}`,
              },
            },
            {
              type: "text",
              text: prompt,
            },
          ],
        },
      ],
    });

    const jsonText = response.choices[0].message.content;

    if (!jsonText) {
      throw new Error("OpenAI returned empty response.");
    }

    const parsed = JSON.parse(jsonText);
    return parsed as ImageAnalysisFlags;
  } catch (error) {
    console.error("Error calling OpenAI:", error);
    throw new Error("Failed to analyze image using OpenAI.");
  }
}
